### ISSUE TITLE
Initiate Submit key

### ISSUE THREAD

**Issue by Cathienna** [SietseT/ElundusCoreApp#12]
Is there a chance to add a key to submit the text to speech with a key, like enter or ctrl+enter.
perhaps add a checkbox to "wipe" the text after submitting as well.

I find this software really nice to use because i am not able to speak and it would be very nice to use on stream and communicate with others instead of writing while playing games and being in VR.

**Comment by SietseT** [comment]
Thanks for the suggestion! 'Enter' to submit and the checkbox to automatically remove the entered text are quite easy things to make. I'll make sure it's added in the next release!

**Comment by SietseT** [comment]
@Cathienna I've added this in the latest release! :)
