### ISSUE TITLE
Suggestion: 32-Bit System Support!

### ISSUE THREAD

**Issue by ksaOfficial** [SietseT/ElundusCoreApp#15]
Can you please make a 32-Bit System for the Elundus Core? Because my system has 32-bit, and i need it

**Comment by SietseT** [comment]
I'll try to see if it's not too much work and if all dependencies support it. What system are you on that it is still 32-bit? 64-bit has been the standard for atleast a decade for Windows.

**Comment by SietseT** [comment]
Closed issue because of inactivity.
