### ISSUE TITLE
Can't Seek With Processed Audio

### ISSUE THREAD

**Issue by Dunebug6** [SietseT/ElundusCoreApp#2]
When you submit a piece of TTS and it processes it into an audio clip that can be played on the right, the resultant audio clip cannot be played at a certain point like you can with the website.

How it should work:
1. Enter text in, press Submit.
2. Sound clip loads on the right.
3. Play soundclip and be able to use the seeker to go to any point in the sound clip.

But, currently instead of being able to go to any point, if you click a point on the seeker, it just continues playing OR it'll revert to the start of the clip instead.

This works fine on the website, but not on the app.
For example, you have a longer dono, you listen, it doesn't sound right, you change a bit, you listen again, but just want to hear the bit you changed so you skip to that part.

**Comment by SietseT** [comment]
Thanks for reporting! I didn't check this behaviour after converting the website. I'll look into it.

**Comment by SietseT** [comment]
Sorry I didn't get back to you earlier. I've been busy deprecating and cleaning up resources of the old website. I'll pick this up as my next task.

**Comment by SietseT** [comment]
I've fixed this issue by developing a custom audio player. It will be included in the next release.
