### ISSUE TITLE
Can't paste anything

### ISSUE THREAD

**Issue by ultimateaviator** [SietseT/ElundusCoreApp#21]
I've created some documents in which I save text that I like to use with Brian. However, when I copy the text from these documents, it won't let me paste them into the text box.

**Comment by SietseT** [comment]
I tried pasting short and long text in the text box and it is working fine for me. It probably has to do with the document that you are copying from. Are you able to paste the text in, for example Notepad?

**Comment by SietseT** [comment]
We haven't heard back from you. Please reply within 7 days or we will close this issue.

**Comment by SietseT** [comment]
Closed because of inactivity.

**Comment by KarimMesallam** [comment]
Pasting functionality is not working, tried pasting from many sources, nothing works, even right-clicking to select paste does nothing. I'm on MacOS Monterey.
