### ISSUE TITLE
Add packages to chocolatey?

### ISSUE THREAD

**Issue by gazwilliams** [SietseT/ElundusCoreApp#31]
I am super duper lazy and wont check for updates manually. An auto update mechanism could also help. If the package was added to choco and maintained it would make it super easy to install and keep up to date :)

https://community.chocolatey.org/

**Comment by SietseT** [comment]
Hi! An auto-updater is built into the application. Doesn't it work? On what platform are you on (Windows I assume)?

**Comment by gazwilliams** [comment]
Sorry the auto updater does work, but I like to manage packages with Chocolatey. It's a nice to have and not essential. I run the update mechanism for Choco regularly to make sure all my apps (notepad++, git etc) are all up to date.

**Comment by SietseT** [comment]
Good to hear the auto-updater is working fine for you! 

However, I currently have no intention to distribute the app with Chocolatey, since I want to keep the amount of maintenance on this project to a minimum. Having to learn Chocolatey and then introducing another complexity to the release process does not fit into that thought.

Sorry!

**Comment by gazwilliams** [comment]
Absolutely fair enough, thanks for taking the time to reply.

**Comment by Emilgardis** [comment]
I made a scoop manifest for Elundus if anyone needs/wants it

```json
{
  "version": "0.6.0",
  "description": "Desktop application to convert text-to-speech to preview Twitch donations. ",
  "homepage": "https://github.com/SietseT/ElundusCoreApp",
  "license": "GPL-3.0",
  "architecture": {
    "64bit": {
      "url": "https://github.com/SietseT/ElundusCoreApp/releases/download/v0.6.0/Elundus-Core-Setup-0.6.0.exe#/dl.7z",
      "hash": "8f95ff2619abd716df655b51c334f82400a729c432339aebe201c18675409c95",
      "pre_install": [
        "Expand-7zipArchive \"$dir\\`$PLUGINSDIR\\app-64.7z\" \"$dir\"",
        "Remove-Item \"$dir\\`$*\", \"$dir\\Uninstall*.exe\" -Recurse -Force"
      ]
    }
  },
  "bin": ["Elundus Core.exe"],
  "shortcuts": [["Elundus Core.exe", "Elundus Core"]],
  "checkver": {
    "github": "https://github.com/SietseT/ElundusCoreApp"
  },
  "autoupdate": {
    "architecture": {
      "64bit": {
        "url": "https://github.com/SietseT/ElundusCoreApp/releases/download/v$version/Elundus-Core-Setup-$version.exe",
        "hash": {
          "url": "$baseurl/latest.yml",
          "regex": "sha512:\\s+$base64"
        }
      }
    }
  }
}
```
