### ISSUE TITLE
Pasting does not work

### ISSUE THREAD

**Issue by KarimMesallam** [SietseT/ElundusCoreApp#32]
I'm on MacOS Monterey.

Pasting functionality is not working. I tried pasting from many sources, nothing works. Even right-clicking does not show the context menu. 

Other related issues:

- command + q to quit does not work.
- command + a to select all does not work.
- command + c to copy does not work.

Seems to me that all of the keyboard shortcuts or any right-clicking is disabled, which makes the software unusable.

**Comment by k3vink3vin** [comment]
The solution to this appears to be adding a context menu.

https://github.com/bitshares/beet/commit/91b31fa5ad733d1df37c7e80be30a00b53b9061a

**Comment by SietseT** [comment]
@KarimMesallam @k3vink3vin  Would either of you be able to contribute a fix? I don't have a Mac and I don't want to add a context menu on all platforms just so that pasting on a Mac works.

**Comment by mmendivilg** [comment]
I was experiencing the same issues on mac, so I fixed it and now it works. Can I contribute my fix?

**Comment by SietseT** [comment]
> 

Of course! Feel free to open a pull-request :)

**Comment by SietseT** [comment]
> I was experiencing the same issues on mac, so I fixed it and now it works. Can I contribute my fix?
Of course! Feel free to open a pull-request :)

**Comment by SietseT** [comment]
Fixed in #37. I'll release this soon.

**Comment by SietseT** [comment]
v0.6.2 has been released with this fix!
