### ISSUE TITLE
Renaming and Saving the file Removes the format and the file gets saved without any format.

### ISSUE THREAD

**Issue by ArchismanKarmakar** [SietseT/ElundusCoreApp#34]
Renaming and Saving the file Removes the format and the file gets saved without any format.
The files in the picture are as 1 2 3 4 5. 

![db](https://user-images.githubusercontent.com/92569441/160297173-4657cc50-9691-4ffe-a72d-35643b3d4176.png)

**Comment by SietseT** [comment]
How are you renaming the file? It seems that you're forgetting to include the format. With the following steps I can rename a file just fine:
1. Click `download`
2. Save the audio file from the browser
3. Rename the file to whatever (and keep the 'Save as type' as MP3!)
4. Save

The file is saved as whatever.mp3 and plays just fine.

**Comment by ArchismanKarmakar** [comment]
> 

Yes if I rename then mp3 extension will go. But windows has a feature to auto determine the file type and irrespective of extension it still automatically adds extensions & that is what I am telling here to fix. Thanks

**Comment by SietseT** [comment]
I don't think this is something I can change, as this is Windows behaviour. If you choose 'All files' in the type dropdown, you **have** to specify an extension in the filename. If you don't, and for example pick 'mp3 file' in the dropdown, Windows appends the `.mp3` extension.
