### ISSUE TITLE
Linux support

### ISSUE THREAD

**Issue by TheHolyTachanka** [SietseT/ElundusCoreApp#35]
**Is your feature request related to a problem? Please describe.**
I dont want to recompile the whole app on every update

**Describe the solution you'd like**
just compile the app for linux too

**Describe alternatives you've considered**
you can compile it yourself

**Additional context**
nothing more

**Comment by SietseT** [comment]
I don't have a Linux machine to build and test this. You're more than welcome to create a PR with this functionality.

**Comment by Master811129** [comment]
> **Is your feature request related to a problem? Please describe.** I dont want to recompile the whole app on every update
> 
> **Describe the solution you'd like** just compile the app for linux too
> 
> **Describe alternatives you've considered** you can compile it yourself
> 
> **Additional context** nothing more

I made an equivalent for this software called VoiceGen. It is available as a flatpak and an AUR package.

**Comment by TheHolyTachanka** [comment]
> I made an equivalent for this software called VoiceGen. It is available as a flatpak and an AUR package.

can i get a link?

**Comment by Master811129** [comment]
> > I made an equivalent for this software called VoiceGen. It is available as a flatpak and an AUR package.
> 
> can i get a link?

[Here](https://gitlab.com/PersianGolf/voicegen) you go.

**Comment by SietseT** [comment]
I will close this issue, since an alternative has been provided.
