### ISSUE TITLE
Increase/remove character limit

### ISSUE THREAD

**Issue by Jornker** [SietseT/ElundusCoreApp#38]
**Is your feature request related to a problem? Please describe.**
I'm trying to generate large batches of text, and the 500 character limit is quite annoying.
**Describe the solution you'd like**
Either remove the character limit altogether, or increase it to 2000

**Comment by SietseT** [comment]
Sadly, the 500 character limit is not enforced by me, but by the API that I use to do the text-to-speech conversion.
