### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by yagalt** [SietseT/ElundusCoreApp#39]
**Describe the bug**
The app gives an error message on launch then launches, but all of my messages return "Something went wrong while reaching the API"

**To Reproduce**
1. Launch Elundus Core
2. See error

**Expected behavior**
I expect the app to launch and turn my text into speech.

**Screenshots**
![image](https://github.com/SietseT/ElundusCoreApp/assets/45718137/77845078-eea6-4e6f-8f7f-b2a3f5d823a1)

**Desktop (please complete the following information):**
 - OS: Windows 11

**Comment by SietseT** [comment]
This is most likely related to your system and could have the following causes:
- Port 5123 is in use by some other program, which causes Elundus Core not being able to use that port
- it could also be related to the `Host Network Service` of Windows 11. See a few possible solutions here: https://stackoverflow.com/a/72936323
