### ISSUE TITLE
[FEATURE] Seems like the API is not rate limited anymore?

### ISSUE THREAD

**Issue by akash-phadtare** [SietseT/ElundusCoreApp#40]
https://api.streamelements.com/kappa/v2/speech?voice=Brian&text=

If there's interest to bring the repo back up, let me know and I can stress test the API to see if it's really not limited anymore.

**Comment by SietseT** [comment]
What do you exactly mean by bringing the repo back up? I haven't done that much maintenance lately, but the app is still up and working fine. Not using streamelements though, but streamlabs.

If you mean having it hosted as a website: I have no intentions of doing that anymore, as that would involve costs and more maintenance from my side.

**Comment by yagalt** [comment]
Well, it could be worth adding the StreamElements version to the app along with the choice to use StreamLabs for when StreamLabs is running slow or when we hit the rate limit

**Comment by SietseT** [comment]
You're always free to open a PR that implements that change. I'll gladly release it! I sadly do not have time or the interest to work on a feature like this.

**Comment by SietseT** [comment]
ElundusCore now uses StreamElements instead of StreamLabs, since StreamLabs can no longer be used and caused issues. See #43.
