### ISSUE TITLE
[FEATURE] Statistics

### ISSUE THREAD

**Issue by yagalt** [SietseT/ElundusCoreApp#42]
I would like to see statistics added to the app as a way to track our usage of the app and how much we type in it. 

I was thinking that some could be 

- Amount of audio files generated
- Amount of words typed 
- Most typed letter
- Total length of everything typed
- Hours elapsed on the app

**Comment by SietseT** [comment]
Hi! Thanks for opening an issue. I do not see much added value in adding this, but you're free to open a PR with these changes.
