### ISSUE TITLE
Keep pasted text on quit and restart

### ISSUE THREAD

**Issue by AndrewPetz** [SietseT/ElundusCoreApp#5]
One of my favorite features of the site was being able to go back to an old tab and keep the same text that was there before. I would love to see the same thing implemented in the desktop version.

**Comment by SietseT** [comment]
Thanks for your suggestion! I'll probably add it in the next release.

**Comment by SietseT** [comment]
@AndrewPetz I've fixed this in the latest release. Thanks for your input :)
