### ISSUE TITLE
Automatically update version in titlebar

### ISSUE THREAD

**Issue by SietseT** [SietseT/ElundusCoreApp#8]
When bumping the version in package.json, the version in the titlebar doesn't automatically update.

**Comment by Escartem** [comment]
There is some ways to read package.json but it only works when the app is in development mode. There was also the `remote` module that was able to do that but it is no longer supported. It would require to downgrade nodejs or electron but it's not worth it just for automatic title I guess. One workaround I think of is use some sort of website that returns the version?

**Comment by SietseT** [comment]
Thanks for the input! Strange that there isn't soms built-in way to get version from package.json. Maybe we can copy the package.json to the output folder during the webpack build? Then we can just read the version from JSON

**Comment by SietseT** [comment]
Fixed in latest release
